#
# Template for what you should write on your deployed VM:s app folder
#

services:
  # .yml for Spinning up a local copy of a database
  henkimaailma_db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - henkimaailma_db
    env_file: .env
    environment:
      - DB_HOST=henkimaailma_db
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: