# Generated by Django 6.1 on 2026-10-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_likeevent'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeevent',
            unique_together={('content_type', 'object_id', 'visitor_hash')},
        ),
    ]
