# Generated by Django 6.1 on 2026-09-03 06:41

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SnSChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -changelog entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundsAndScapesPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('external_url', models.URLField(help_text='Link to where the sample pack is downloadable from')),
                ('licence', models.CharField(choices=[('cc0', 'CC0 Creative Commons Licence'), ('all_rights_reserved', 'All rights reserved')], default='all_rights_reserved', max_length=255)),
                ('file_list', models.JSONField(blank=True, default=dict)),
                ('release_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='sns_samplepacks', to='content.tag')),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -sample packs',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('streaming_links', models.JSONField(blank=True, default=dict)),
                ('release_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='music_release', to='content.tag')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default='fi', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('ingress', models.TextField(blank=True)),
                ('body_markdown', models.TextField(blank=True)),
                ('article_image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('blog', 'Blog post'), ('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('project_writeup', 'Project writeup')], max_length=255)),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5'), (2, '1'), (3, '1,5'), (4, '2'), (5, '2,5'), (6, '3'), (7, '3,5'), (8, '4'), (9, '4,5'), (10, '5')], help_text='Only fill if the article is a review', null=True)),
                ('external_url', models.URLField(blank=True)),
                ('published_date', models.DateField()),
                ('article_extras', models.JSONField(blank=True, default=content.models.articleextras_defaults)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.tag')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_id', models.CharField(max_length=11, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('internal_title', models.CharField(max_length=255)),
                ('content_language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default='fi', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('video_essay', 'Video essay'), ('vlog', 'Vlog'), ('commentary', 'Commentary video')], max_length=100)),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5'), (2, '1'), (3, '1,5'), (4, '2'), (5, '2,5'), (6, '3'), (7, '3,5'), (8, '4'), (9, '4,5'), (10, '5')], help_text='Only fill if the video is a review', null=True)),
                ('published_date', models.DateField()),
                ('video_extras', models.JSONField(blank=True, default=content.models.videoextras_defaults, help_text='For example rating if the video is a review.')),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='youtube_videos', to='content.tag')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('translated_title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('ingress', models.TextField(blank=True)),
                ('body_markdown', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.article')),
            ],
            options={
                'verbose_name_plural': 'article translations',
                'unique_together': {('article', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('translated_title', models.CharField(blank=True, max_length=255)),
                ('body_markdown', models.TextField()),
                ('changelog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.changelogentry')),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'unique_together': {('changelog_entry', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MusicReleaseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.musicrelease')),
            ],
            options={
                'verbose_name_plural': 'music release translations',
                'unique_together': {('release', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SnSChangelogEntryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('title', models.CharField(default='', max_length=255)),
                ('body_markdown', models.TextField()),
                ('changelog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.snschangelogentry')),
            ],
            options={
                'verbose_name_plural': 'SnS Changelog Entries',
                'unique_together': {('changelog_entry', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SoundsAndScapesPackDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('snspack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.soundsandscapespack')),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -sample pack translations',
                'unique_together': {('snspack', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('translated_title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('translated_video_subtitles', models.BooleanField(default=False)),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.video')),
            ],
            options={
                'verbose_name_plural': 'video translations',
                'unique_together': {('youtube_video', 'language')},
            },
        ),
    ]
