# Generated by Django 6.1 on 2026-08-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundsAndScapesPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('external_url', models.URLField()),
                ('file_list', models.JSONField(blank=True, default=dict)),
                ('release_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='sns_samplepacks', to='content.tag')),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -sample packs',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('streaming_links', models.JSONField(blank=True, default=dict)),
                ('release_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='music_release', to='content.tag')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('article_image_url', models.URLField(blank=True)),
                ('article_category', models.CharField(choices=[('blog', 'blog post'), ('game_review', 'game review'), ('music_review', 'music review'), ('film_review', 'film review'), ('tv_review', 'tv review'), ('project_writeup', 'project writeup')])),
                ('external_url', models.URLField(blank=True)),
                ('published_date', models.DateField()),
                ('article_extras', models.JSONField(blank=True, default=dict)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.tag')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_id', models.CharField(max_length=11, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('game_review', 'game review'), ('video_essay', 'video essay'), ('vlog', 'vlog'), ('commentary', 'commentary')], max_length=100)),
                ('video_language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('published_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='youtube_videos', to='content.tag')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('summary', models.TextField()),
                ('body_markdown', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.article')),
            ],
            options={
                'verbose_name_plural': 'article translations',
                'unique_together': {('article', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('body_markdown', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('changelogEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.changelogentry')),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'unique_together': {('changelogEntry', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MusicReleaseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.musicrelease')),
            ],
            options={
                'verbose_name_plural': 'music release translations',
                'unique_together': {('release', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SoundsAndScapesPackDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('snspack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.soundsandscapespack')),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -sample pack translations',
                'unique_together': {('snspack', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('translated_title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.video')),
            ],
            options={
                'verbose_name_plural': 'video translations',
                'unique_together': {('youtube_video', 'language')},
            },
        ),
    ]
