# Generated by Django 6.1 on 2026-08-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('blog', 'Blog post'), ('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('project_writeup', 'Project writeup')]),
        ),
    ]
