# Generated by Django 6.1 on 2026-09-11 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('blog', 'Blog post'), ('game_review', 'Game review'), ('music_review', 'Music review'), ('book_review', 'Book review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('project_writeup', 'Project writeup')], max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('book_review', 'Book review'), ('video_essay', 'Video essay'), ('vlog', 'Vlog'), ('commentary', 'Commentary video')], max_length=100),
        ),
    ]
