# Generated by Django 6.1 on 2026-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='soundsandscapespack',
            name='external_url',
            field=models.URLField(help_text='Link to where the sample pack is downloadable from'),
        ),
    ]
