# Generated by Django 6.1 on 2026-09-11 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_updated_date_alter_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
