# Generated by Django 6.1 on 2026-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_slug_alter_soundsandscapespack_external_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='internal_title',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('game_review', 'Game review'), ('video_essay', 'Video essay'), ('vlog', 'Vlog'), ('commentary', 'Commentary video')], max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3),
        ),
    ]
