# Generated by Django 6.1 on 2026-09-11 09:49

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_extras',
            field=models.JSONField(blank=True, default=content.models.articleextras_defaults, null=True),
        ),
    ]
