# Generated by Django 6.1 on 2026-08-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_title_video_internal_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnSChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sounds and Scapes -changelog entries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='soundsandscapespack',
            name='licence',
            field=models.CharField(choices=[('cc0', 'CC0 Creative Commons Licence'), ('all_rights_reserved', 'All rights reserved')], default='all_rights_reserved', max_length=255),
        ),
        migrations.CreateModel(
            name='SnSChangelogEntryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('body_markdown', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('changelogEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.snschangelogentry')),
            ],
            options={
                'verbose_name_plural': 'SnS Changelog Entries',
                'unique_together': {('changelogEntry', 'language')},
            },
        ),
    ]
