# Generated by Django 6.1 on 2026-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_article_article_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_extras',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_extras',
            field=models.JSONField(blank=True, help_text='For example rating if the video is a review.', null=True),
        ),
    ]
