# Generated by Django 6.1 on 2026-08-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_snschangelogentry_soundsandscapespack_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundsandscapespack',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
