# Generated by Django 6.1 on 2026-09-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_article_article_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicrelease',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
