# Generated by Django 6.1 on 2026-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_soundsandscapespack_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsandscapespack',
            name='updated_date',
            field=models.DateField(),
        ),
    ]
