# Generated by Django 6.1 on 2026-09-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_musicrelease_extras_alter_article_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Use Finnish as default language.', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=3)),
                ('tname', models.CharField(max_length=50)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.tag')),
            ],
            options={
                'verbose_name_plural': 'Tag name translations',
                'unique_together': {('tag', 'language')},
            },
        ),
    ]
