# Generated by Django 6.1 on 2026-08-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_soundsandscapespack_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelogentrytranslation',
            old_name='changelogEntry',
            new_name='changelog_entry',
        ),
        migrations.RenameField(
            model_name='snschangelogentrytranslation',
            old_name='changelogEntry',
            new_name='changelog_entry',
        ),
        migrations.AlterUniqueTogether(
            name='changelogentrytranslation',
            unique_together={('changelog_entry', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='snschangelogentrytranslation',
            unique_together={('changelog_entry', 'language')},
        ),
    ]
