# Generated by Django 6.1 on 2026-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_tag_name_tagtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_title',
            field=models.CharField(blank=True),
        ),
    ]
