# Generated by Django 6.1 on 2026-08-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_changelogentry_changelogentrytranslation_changelog_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelogentrytranslation',
            name='tags',
        ),
    ]
