# Generated by Django 6.1 on 2026-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_changelogentrytranslation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentrytranslation',
            name='translated_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('blog', 'Blog post'), ('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('project_writeup', 'Project writeup')], max_length=255),
        ),
    ]
