# Generated by Django 6.1 on 2026-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_henkimaailmapage_viewcount_viewevent'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HenkimaailmaPage',
            new_name='GenericPage',
        ),
        migrations.RemoveIndex(
            model_name='viewevent',
            name='content_vie_content_0b5de6_idx',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='viewcount',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='viewevent',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='object_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddIndex(
            model_name='viewevent',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='content_vie_content_45a1c7_idx'),
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='object_slug',
        ),
    ]
