# Generated by Django 6.1 on 2026-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_changelogentrytranslation_translated_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
