# Generated by Django 6.1 on 2026-09-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_henkimaailmapage_genericpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
