# Generated by Django 6.1 on 2026-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_video_video_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_extras',
            field=models.JSONField(blank=True, default={'rating': None}, help_text='For example rating if the video is a review.'),
        ),
    ]
