# Generated by Django 6.1 on 2026-09-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_genericpage_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewcount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='content_type',
        ),
        migrations.RemoveIndex(
            model_name='viewevent',
            name='content_vie_content_45a1c7_idx',
        ),
        migrations.DeleteModel(
            name='ViewCount',
        ),
        migrations.DeleteModel(
            name='ViewEvent',
        ),
    ]
