# Generated by Django 6.1 on 2026-10-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_viewcount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musicrelease',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soundsandscapespack',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
