# Generated by Django 6.1 on 2026-08-28 07:31

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_video_video_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_extras',
            field=models.JSONField(blank=True, default=content.models.articleextras_defaults),
        ),
    ]
