# Generated by Django 6.1 on 2026-08-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_article_article_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletranslation',
            name='summary',
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='translated_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='body_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('game_review', 'Game review'), ('music_review', 'Music review'), ('film_review', 'Film review'), ('tv_review', 'TV review'), ('video_essay', 'Video essay'), ('vlog', 'Vlog'), ('commentary', 'Commentary video')], max_length=100),
        ),
    ]
