# Generated by Django 6.1 on 2026-08-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_articletranslation_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category',
            new_name='category',
        ),
    ]
