# Generated by Django 6.1 on 2026-08-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_rename_article_category_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_language',
        ),
        migrations.AddField(
            model_name='article',
            name='content_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default='fi', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default='fi', max_length=3),
        ),
    ]
