# Generated by Django 6.1 on 2026-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5 stars'), (2, '1 stars'), (3, '1,5 stars'), (4, '2 stars'), (5, '2,5 stars'), (6, '3 stars'), (7, '3,5 stars'), (8, '4 stars'), (9, '4,5 stars'), (10, '5 stars')], help_text='Only fill if the article is a review', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5 stars'), (2, '1 stars'), (3, '1,5 stars'), (4, '2 stars'), (5, '2,5 stars'), (6, '3 stars'), (7, '3,5 stars'), (8, '4 stars'), (9, '4,5 stars'), (10, '5 stars')], help_text='Only fill if the video is a review', null=True),
        ),
    ]
