# Generated by Django 6.1 on 2026-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_article_body_markdown_article_rating_video_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ingress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='ingress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5'), (2, '1'), (3, '1,5'), (4, '2'), (5, '2,5'), (6, '3'), (7, '3,5'), (8, '4'), (9, '4,5'), (10, '5')], help_text='Only fill if the article is a review', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No stars'), (1, '0,5'), (2, '1'), (3, '1,5'), (4, '2'), (5, '2,5'), (6, '3'), (7, '3,5'), (8, '4'), (9, '4,5'), (10, '5')], help_text='Only fill if the video is a review', null=True),
        ),
    ]
