# Generated by Django 6.1 on 2026-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_article_ingress_articletranslation_ingress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranslation',
            name='translated_video_subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
