# Generated by Django 6.1 on 2026-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_videotranslation_translated_video_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='snschangelogentrytranslation',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
