# Generated by Django 6.1 on 2026-09-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_snschangelogentrytranslation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snschangelogentrytranslation',
            name='tags',
        ),
    ]
